language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# command to run tests
script: pytest
